url: https://horlixuk.github.io


# Site settings
title: Monsters of Wedrock
email: hello@monstersofwedrock.co.uk
description: "wedding website for Izzi and Mark"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty

include: ['_en_pages', '_fr_pages']